---
- name: Infrastructure Health Check
  hosts: all
  gather_facts: true
  tasks:
    - name: Print system uptime using native Ansible Facts
      ansible.builtin.debug:
        msg: "The server has been up for {{ ansible_uptime_seconds }} seconds."

    - name: Create a status file on the target machine
      ansible.builtin.copy:
        content: "Automated successfully by AWX inside Kind!\n"
        dest: /tmp/awx_status.txt
