---
- name: Infrastructure Identity and Security Management
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure group 'sysadmin' exists
      ansible.builtin.group:
        name: sysadmin
        state: present

    - name: Create DevOps Administrator user
      ansible.builtin.user:
        name: devopsadmin
        comment: "Automation Managed Account"
        group: sysadmin
        groups: sudo   # Nota: Si tu VPS usa RHEL/Rocky, cambia 'sudo' por 'wheel'
        append: true
        shell: /bin/bash
        state: present

    - name: Verify user creation by checking passwd
      ansible.builtin.command: getent passwd devopsadmin
      register: user_check
      changed_when: false

    - name: Show user details in AWX console
      ansible.builtin.debug:
        var: user_check.stdout
