---
- name: Ensure Mount Point Directory Exists
  ansible.builtin.file:
    path: "{{ mount_point }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure Filesystem in fstab
  ansible.builtin.mount:
    path: "{{ mount_point }}"
    src: "{{ disk_source }}"
    fstype: "{{ filesystem_type }}"
    opts: "bind,defaults,noatime"  # <- Agregamos 'bind' al inicio de las opciones
    state: present
  notify: Trigger Mount All Filesystems
