---
- name: Ensure Mount Point Directory Exists
  ansible.builtin.file:
    path: "{{ mount_point }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure Filesystem in fstab
  ansible.builtin.mount:
    path: "{{ mount_point }}"
    src: "{{ disk_source }}"
    fstype: "{{ filesystem_type }}"
    opts: "defaults,noatime"
    state: present  # 'present' solo escribe el archivo /etc/fstab, NO lo monta de inmediato.
  notify: Trigger Mount All Filesystems  # <- CLAVE: Si la línea en /etc/fstab ya existía exacta, no hace nada. Si cambió o es nueva, activa el handler para montar el disco.
